### ISSUE TITLE
Error trying to make this work on WSL

### ISSUE THREAD

**Issue by vico93** [callmekatootie/spool#2]
Basically, i'm trying to test this on my WSL instance in my Windows 11, but seems like something i'm doing is broken and i dont know exacly why.

After reading the documentation of next, [i saw that i need to do](https://nextjs.org/docs/app/api-reference/next-cli#production) `npx next build` first before running spool. But when i try to do that command, this happens:

```
npx next build
- info Loaded env from /home/vico/.spool/.env
- info Linting and checking validity of types .Failed to compile.

./components/Thread/index.tsx:59:10
Type error: Property 'isQuotedPost' is missing in type '{ handle: string; profilePic: string; }' but required in type '{ isQuotedPost: boolean; }'.

  57 |           isLeafNode={isLeafNode}
  58 |         />
> 59 |         <ProfilePic handle={handle} profilePic={profilePic} />
     |          ^
  60 |         <ThreadLink isInternalNode={isInternalNode} isRootNode={isRootNode} />
  61 |       </div>
  62 |       <div
- info Linting and checking validity of types
```

**Comment by callmekatootie** [comment]
I can reproduce this issue only during build and not during `npm run dev`. 

However, I cannot make any changes atm. The API this app was relying on was a third party one, and it is no longer available. The app will most definitely get updated once Threads comes out with their official api. Until then, there isn't anything to do.
